### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jkbest2** [jkbest2/spatq#1]
# Minimum viable package

The initial goal is for the package to provide the shared library (TMB program). R code will be limited to tests. Data and parameter arguments will be constructed manually, and then the standard TMB workflow will apply (i.e. `MakeADFun` will be called by the user). The following components of the model will be built up sequentially:

- [x] log-normal regression
- [x] add spatial process
- [x] add zero inflation using Poisson link
- [x] add spatially varying catchability
- [x] add index calculation

Along the way simulation components will be included so that the model can generate data for testing. These will be used for testing, and the R code based tests will likely be removed.

# R interface

Once the model is established, an R interface capable of taking a data frame, model specification, and INLA mesh will be written to format data, parameter, and map arguments to be passed to the model. In particular, checking for consistent dimensions should prevent crashes when the model is called.

**Comment by jkbest2** [comment]
All above features now included.
